using System.Globalization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using WalkingPatterns.Api.Data;

namespace WalkingPatterns.Api.Controllers;

[ApiController, Route("api/projects")]
public sealed class QuotationController : ControllerBase
{
    private readonly AppDbContext context; private readonly IWebHostEnvironment environment;
    public QuotationController(AppDbContext context, IWebHostEnvironment environment) { this.context = context; this.environment = environment; }

    [HttpGet("{projectId:int}/quotation")]
    public async Task<IActionResult> Generate(int projectId)
    {
        var project = await context.ProjectVersionDetails.Include(x => x.Client).SingleOrDefaultAsync(x => x.Id == projectId);
        if (project == null) return NotFound(new { message = "Project not found." });
        var details = await context.ProjectDetails.AsNoTracking().Where(x => x.ProjectId == projectId).ToListAsync();
        var orders = await context.OrderDetails.AsNoTracking().Where(x => x.ProjectVersionDetailsId == projectId && x.ProjectId == projectId).ToListAsync();
        var total = orders.Sum(x => x.TotalPrice); var discount = Math.Clamp(project.DiscountAmount, 0, total); var net = Math.Max(0, total - discount);
        var logo = Path.Combine(environment.WebRootPath ?? environment.ContentRootPath, "WalkingPatterns-logo.png");
        var pdf = Document.Create(root => root.Page(page => { page.Size(PageSizes.A4); page.Margin(10); page.DefaultTextStyle(x => x.FontFamily("Arial").FontSize(10)); page.Content().Column(c => { c.Spacing(8); c.Item().Text("Order Quotation").FontSize(16).Bold().FontColor(Colors.Grey.Darken3).AlignCenter(); c.Item().Element(x => Header(x, project, logo)); c.Item().LineHorizontal(1); c.Item().Element(x => Client(x, project)); c.Item().LineHorizontal(1); c.Item().Element(x => Summary(x, details)); c.Item().Element(x => Prices(x, total, discount, net)); c.Item().PageBreak(); Orders(c, orders); c.Item().PageBreak(); Terms(c); }); }));
        return File(pdf.GeneratePdf(), "application/pdf", $"{Safe(project.Client.ClientName)}_{Safe(project.VersionNumber)}.pdf");
    }

    static void Header(IContainer c, Models.ProjectVersionDetails p, string logo) => c.Row(r => { r.RelativeItem().Height(60).Element(x => { if (System.IO.File.Exists(logo)) x.Image(System.IO.File.ReadAllBytes(logo)).FitArea(); }); r.RelativeItem(2).AlignRight().Column(x => { Row(x, "Architect:", "Sahana S"); Row(x, "Email:", "sahanasathish@walkingpatterns.com"); Row(x, "Phone:", "9611917967"); Row(x, "Date:", DateTime.Now.ToString("dd/MM/yyyy")); Row(x, "Version:", p.VersionNumber); }); });
    static void Row(ColumnDescriptor c, string label, string value) => c.Item().Row(r => { r.RelativeItem().AlignRight().Text(label).Bold(); r.RelativeItem().Text(value); });
    static void Client(IContainer c, Models.ProjectVersionDetails p) => c.Column(x => { x.Item().Background(Colors.Black).Padding(8).AlignCenter().Text("Client Details").FontColor(Colors.White).Bold(); x.Item().Table(t => { t.ColumnsDefinition(d => { d.RelativeColumn(); d.RelativeColumn(2); }); foreach (var v in new[] { ("Client Name:", p.Client.ClientName), ("Email:", p.Client.Email ?? "N/A"), ("Phone:", p.Client.Phone ?? "N/A"), ("Address:", p.Client.Address ?? "N/A") }) { t.Cell().Element(Label).Text(v.Item1); t.Cell().Element(Label).Text(v.Item2); } }); });
    static void Summary(IContainer c, List<Models.ProjectDetails> d) => c.Column(x => { x.Item().Background(Colors.Black).Padding(8).AlignCenter().Text("Project Details").FontColor(Colors.White).Bold(); x.Item().Table(t => { t.ColumnsDefinition(cd => { for (var i = 0; i < 5; i++) cd.RelativeColumn(); }); foreach (var h in new[] { "Room Name", "Woodwork", "Accessories", "Services", "Total" }) t.Cell().Element(Header).Text(h); foreach (var g in d.GroupBy(i => i.RoomName)) { var a = g.Sum(i => Parse(i.Accessories)); var s = g.Sum(i => Parse(i.Services)); var n = g.Sum(i => Parse(i.Total)); foreach (var v in new[] { g.Key, Money(n-a-s), Money(a), Money(s), Money(n) }) t.Cell().Element(Data).Text(v); } t.Cell().ColumnSpan(4).Element(Grand).AlignRight().Text("Grand Total:").Bold(); t.Cell().Element(Grand).Text(Money(d.Sum(i => Parse(i.Total)))).Bold(); }); });
    static void Prices(IContainer c, double total, double discount, double net) => c.Column(x => { x.Item().Text("Price Summary").Bold().FontSize(12); x.Item().Table(t => { t.ColumnsDefinition(d => { d.RelativeColumn(); d.RelativeColumn(); }); Price(t, "Total Amount:", Money(total), false); Price(t, "(-) Discount Amount:", Money(discount), false); Price(t, "Grand Total:", Money(net), true); }); });
    static void Price(TableDescriptor t, string label, string value, bool red) { t.Cell().Element(red ? Grand : Label).Text(label).Bold(); t.Cell().Element(red ? Grand : Label).AlignRight().Text(value).Bold().FontColor(red ? Colors.Red.Medium : Colors.Black); }
    static void Orders(ColumnDescriptor c, List<Models.OrderDetails> orders) { var order = new[] { "KitchenUtility", "Bedroom", "Other Woodwork", "HDS", "Other" }; foreach (var g in orders.GroupBy(x => Module(x.UtilityNameOld)).OrderBy(x => Array.IndexOf(order, x.Key) < 0 ? 4 : Array.IndexOf(order, x.Key))) { c.Item().Text($"{g.Key} Summary").FontSize(13).Bold(); c.Item().Text($"Total Amount: {Money(g.Sum(x => x.TotalPrice))}").FontColor(Colors.Red.Medium).Bold(); foreach (var room in g.GroupBy(x => x.UtilityName)) { c.Item().Text(room.Key ?? "N/A").Underline().AlignCenter(); c.Item().Table(t => { t.ColumnsDefinition(d => { for (var i = 0; i < 6; i++) d.RelativeColumn(); }); foreach (var h in new[] { "Product Name", "Finish", "Accessories & Quantity", "Additional Items & Quantity", "Dimensions", "Total" }) t.Cell().Element(Header).Text(h); foreach (var i in room) foreach (var v in new[] { i.Parent ?? "N/A", Materials(i.Materials), Pair(i.Accessories, i.Quantities), Pair(i.AdditionalItemName, i.AdditionalItemsQuantities), $"{i.Width} x {i.Height} x {i.Depth}", Money(i.TotalPrice) }) t.Cell().Element(Data).Text(v); }); } } }
    static void Terms(ColumnDescriptor c) { c.Item().Background(Colors.Black).Padding(8).AlignCenter().Text("Terms and Conditions").FontColor(Colors.White).Bold(); c.Item().Text("1. The quotation is an initial estimate and is valid for 4 months from the date of generation of quotation.\n2. The exact price of your project will depend on measurements, scope of work and change in designs/material/finishes.\n3. Based on the above revisions, you can expect the quote to raise or drop by approximately 10-15%.\n4. To move forward with the development of measurement-based designs, you will have to pay 10% of this estimate.\n5. The initial estimates may not include civil,plumbing,gas-piping,electrical work.The exact value of the quote will depend on the site conditions.\n6. Post installation, the following set of services will be done at the site:\n    a. Dusting, sweeping and mopping of all areas.\n    b. Cleaning of doors of the cabinets to remove pencil marks and dust.\n    c. Cleaning the insides of wooden cabinets.\n    d. Deep cleaning of washroom.\n7. Mechanized cleaning is out of scope.\n8. The Price structure has 4 Installments:\n    a. First Installment – 10% of the quote value – Order booking.\n    b. Second Installment - 15% of the quote value- First cut design finalization.\n    c. Third Installment – 25% of the quote value- Complete Design finalization including working drawings.\n    d. Fourth/Final Installment – Remaining 50%- Before the start of production at the factory.\n9. All woodwork is covered under 10 years warranty.\n10. All accessories, hardware, appliances etc. are covered as per respective Manufacturer’s Warranty Policy.\n11. All other items like mirror,glass,counter top material,gas piping,tiles and other civil works are provided on an as-is basis,without warranties.\n12. Cancellation policy:\n    a. Pre design stage - within 48 hours from order booking and if site measurements and first design discussion has not happened - 100% refund.\n    b. Design stage and beyond - No refund.\n13. Brands Associated (but not limited to):\n    a. Plywood and MDF - Centuryply, Greenply, Action Tesa, Greenpanel.\n    b. Laminate- Merino, Royal Touche, Century.\n    c. Hardware and Accessories- Hettich, Ebco, Hafele, Blum, Everyday, Spitze.\n    d. Glass and Mirror- Saint Gobain, Modi Guard.\n    e. Painting- Asian Paints, Berger Paints.\n    f. Appliances- Elica, Faber, Futura, Hafele, Bosch, Glen, Kaff.\n    g. Lighting- Philips, GM, Wipro, Havells."); c.Item().PaddingTop(12).Table(t => { t.ColumnsDefinition(d => { for (var i = 0; i < 4; i++) d.RelativeColumn(); }); foreach (var h in new[] { "Account Name", "Bank Name", "Account Number", "IFSC and Branch" }) t.Cell().Element(Header).Text(h); foreach (var v in new[] { "Sandeep K", "ICICI", "777701905796", "ICIC0006254, Chamrajpete" }) t.Cell().Element(Data).Text(v); }); }
    static IContainer Label(IContainer c) => c.BorderBottom(.5f).Padding(4); static IContainer Header(IContainer c) => c.Background(Colors.Grey.Lighten2).Border(.5f).Padding(5).AlignCenter(); static IContainer Data(IContainer c) => c.BorderBottom(.5f).Padding(4).AlignCenter(); static IContainer Grand(IContainer c) => c.Background(Colors.Grey.Lighten2).Border(.5f).Padding(5);
    static double Parse(string? v) => double.TryParse(v, NumberStyles.Any, CultureInfo.InvariantCulture, out var n) ? n : 0; static string Money(double v) => $"Rs. {v.ToString("N2", CultureInfo.GetCultureInfo("en-IN"))}"; static string Materials(string? v) => string.IsNullOrWhiteSpace(v) ? "N/A" : string.Join("\n", v.Split(',').Select(x => x.Trim()).Where(x => x.Length > 0));
    static string Pair(string? v, string? q) { var a = (v ?? "").Split(','); var b = (q ?? "").Split(','); var r = new List<string>(); for (var i = 0; i < a.Length; i++) if (!string.IsNullOrWhiteSpace(a[i]) && a[i].Trim() != "0") r.Add($"{a[i].Trim()} - {b.ElementAtOrDefault(i)?.Trim() ?? "N/A"}"); return r.Count == 0 ? "N/A" : string.Join("\n", r); }
    static string Module(string? v) => v?.StartsWith("KitchenUtility", StringComparison.OrdinalIgnoreCase) == true ? "KitchenUtility" : v?.StartsWith("Bedroom", StringComparison.OrdinalIgnoreCase) == true ? "Bedroom" : v?.StartsWith("Other Woodwork", StringComparison.OrdinalIgnoreCase) == true ? "Other Woodwork" : v?.StartsWith("HDS", StringComparison.OrdinalIgnoreCase) == true ? "HDS" : "Other"; static string Safe(string v) { var invalid = Path.GetInvalidFileNameChars(); return new string(v.Select(ch => invalid.Contains(ch) ? '_' : ch).ToArray()); }
}
